# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/rcampos/co-diseno/labo6_try2/solution1/impl/verilog/project.cache/wt [current_project]
set_property parent.project_path /home/rcampos/co-diseno/labo6_try2/solution1/impl/verilog/project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/rcampos/co-diseno/labo6_try2/solution1/impl/verilog/mul_AXILiteS_s_axi.v
  /home/rcampos/co-diseno/labo6_try2/solution1/impl/verilog/mul.v
}
read_xdc /home/rcampos/co-diseno/labo6_try2/solution1/impl/verilog/mul.xdc
set_property used_in_implementation false [get_files /home/rcampos/co-diseno/labo6_try2/solution1/impl/verilog/mul.xdc]

synth_design -top mul -part xc7z010clg400-1 -no_iobuf -mode out_of_context
write_checkpoint -noxdef mul.dcp
catch { report_utilization -file mul_utilization_synth.rpt -pb mul_utilization_synth.pb }
