// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xrgb_to_bw.h"

extern XRgb_to_bw_Config XRgb_to_bw_ConfigTable[];

XRgb_to_bw_Config *XRgb_to_bw_LookupConfig(u16 DeviceId) {
	XRgb_to_bw_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XRGB_TO_BW_NUM_INSTANCES; Index++) {
		if (XRgb_to_bw_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XRgb_to_bw_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XRgb_to_bw_Initialize(XRgb_to_bw *InstancePtr, u16 DeviceId) {
	XRgb_to_bw_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XRgb_to_bw_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XRgb_to_bw_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

