// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xrgb_to_bw.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XRgb_to_bw_CfgInitialize(XRgb_to_bw *InstancePtr, XRgb_to_bw_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XRgb_to_bw_Start(XRgb_to_bw *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_AP_CTRL) & 0x80;
    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XRgb_to_bw_IsDone(XRgb_to_bw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XRgb_to_bw_IsIdle(XRgb_to_bw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XRgb_to_bw_IsReady(XRgb_to_bw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XRgb_to_bw_EnableAutoRestart(XRgb_to_bw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XRgb_to_bw_DisableAutoRestart(XRgb_to_bw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XRgb_to_bw_Get_return(XRgb_to_bw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_AP_RETURN);
    return Data;
}
void XRgb_to_bw_Set_red(XRgb_to_bw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_RED_DATA, Data);
}

u32 XRgb_to_bw_Get_red(XRgb_to_bw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_RED_DATA);
    return Data;
}

void XRgb_to_bw_Set_green(XRgb_to_bw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_GREEN_DATA, Data);
}

u32 XRgb_to_bw_Get_green(XRgb_to_bw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_GREEN_DATA);
    return Data;
}

void XRgb_to_bw_Set_blue(XRgb_to_bw *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_BLUE_DATA, Data);
}

u32 XRgb_to_bw_Get_blue(XRgb_to_bw *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_BLUE_DATA);
    return Data;
}

void XRgb_to_bw_InterruptGlobalEnable(XRgb_to_bw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_GIE, 1);
}

void XRgb_to_bw_InterruptGlobalDisable(XRgb_to_bw *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_GIE, 0);
}

void XRgb_to_bw_InterruptEnable(XRgb_to_bw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_IER);
    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_IER, Register | Mask);
}

void XRgb_to_bw_InterruptDisable(XRgb_to_bw *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_IER);
    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_IER, Register & (~Mask));
}

void XRgb_to_bw_InterruptClear(XRgb_to_bw *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XRgb_to_bw_WriteReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_ISR, Mask);
}

u32 XRgb_to_bw_InterruptGetEnabled(XRgb_to_bw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_IER);
}

u32 XRgb_to_bw_InterruptGetStatus(XRgb_to_bw *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XRgb_to_bw_ReadReg(InstancePtr->Axilites_BaseAddress, XRGB_TO_BW_AXILITES_ADDR_ISR);
}

