#pragma line 1 "labo6_files/rgb_to_bw.cpp" ::: 0
#pragma line 1 "labo6_files/rgb_to_bw.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 10
#pragma line 145 "/opt/Xilinx/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 63
#pragma line 404 "/opt/Xilinx/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 195
#pragma line 6 "<command line>" 2 ::: 198
#pragma line 1 "<built-in>" 2 ::: 199
#pragma line 1 "labo6_files/rgb_to_bw.cpp" 2 ::: 200
