#pragma line 1 "labo6_files/rgb_to_bw.cpp" ::: -10
#pragma line 1 "labo6_files/rgb_to_bw.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 0
#pragma line 145 "/opt/Xilinx/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 53
#pragma line 404 "/opt/Xilinx/Vivado_HLS/2015.2/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 185
#pragma line 6 "<command line>" 2 ::: 188
#pragma line 1 "<built-in>" 2 ::: 189
#pragma line 1 "labo6_files/rgb_to_bw.cpp" 2 ::: 190
#pragma line 6 "labo6_files/rgb_to_bw.cpp" ::: 198
#pragma line 6 "labo6_files/rgb_to_bw.cpp" ::: 201
#pragma line 6 "labo6_files/rgb_to_bw.cpp" ::: 204
#pragma line 6 "labo6_files/rgb_to_bw.cpp" ::: 207
