// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.2
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XRGB_TO_BW_H
#define XRGB_TO_BW_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xrgb_to_bw_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XRgb_to_bw_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XRgb_to_bw;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XRgb_to_bw_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XRgb_to_bw_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XRgb_to_bw_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XRgb_to_bw_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XRgb_to_bw_Initialize(XRgb_to_bw *InstancePtr, u16 DeviceId);
XRgb_to_bw_Config* XRgb_to_bw_LookupConfig(u16 DeviceId);
int XRgb_to_bw_CfgInitialize(XRgb_to_bw *InstancePtr, XRgb_to_bw_Config *ConfigPtr);
#else
int XRgb_to_bw_Initialize(XRgb_to_bw *InstancePtr, const char* InstanceName);
int XRgb_to_bw_Release(XRgb_to_bw *InstancePtr);
#endif

void XRgb_to_bw_Start(XRgb_to_bw *InstancePtr);
u32 XRgb_to_bw_IsDone(XRgb_to_bw *InstancePtr);
u32 XRgb_to_bw_IsIdle(XRgb_to_bw *InstancePtr);
u32 XRgb_to_bw_IsReady(XRgb_to_bw *InstancePtr);
void XRgb_to_bw_EnableAutoRestart(XRgb_to_bw *InstancePtr);
void XRgb_to_bw_DisableAutoRestart(XRgb_to_bw *InstancePtr);
u32 XRgb_to_bw_Get_return(XRgb_to_bw *InstancePtr);

void XRgb_to_bw_Set_red(XRgb_to_bw *InstancePtr, u32 Data);
u32 XRgb_to_bw_Get_red(XRgb_to_bw *InstancePtr);
void XRgb_to_bw_Set_green(XRgb_to_bw *InstancePtr, u32 Data);
u32 XRgb_to_bw_Get_green(XRgb_to_bw *InstancePtr);
void XRgb_to_bw_Set_blue(XRgb_to_bw *InstancePtr, u32 Data);
u32 XRgb_to_bw_Get_blue(XRgb_to_bw *InstancePtr);

void XRgb_to_bw_InterruptGlobalEnable(XRgb_to_bw *InstancePtr);
void XRgb_to_bw_InterruptGlobalDisable(XRgb_to_bw *InstancePtr);
void XRgb_to_bw_InterruptEnable(XRgb_to_bw *InstancePtr, u32 Mask);
void XRgb_to_bw_InterruptDisable(XRgb_to_bw *InstancePtr, u32 Mask);
void XRgb_to_bw_InterruptClear(XRgb_to_bw *InstancePtr, u32 Mask);
u32 XRgb_to_bw_InterruptGetEnabled(XRgb_to_bw *InstancePtr);
u32 XRgb_to_bw_InterruptGetStatus(XRgb_to_bw *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
